import { mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import SQLite from 'better-sqlite3';
import { CamelCasePlugin, Kysely, ParseJSONResultsPlugin, SqliteDialect } from 'kysely';
import { generate as generateSchema, SqliteDialect as CodegenSqliteDialect } from 'kysely-codegen';
import { round, run } from '$lib/utils/utils.js';
import fs from 'node:fs/promises';
import path from 'node:path';
import { FileMigrationProvider, Migrator } from 'kysely/migration';

export type CreateDatabaseServicesOptions = {
  file: string;
  wal?: boolean;
  migrations: string;
};

export const createDatabaseServices = async <D = unknown>(opts: CreateDatabaseServicesOptions) => {
  const { file: filename, wal = true, migrations } = opts;

  const sqlite = await run(async () => {
    if (filename !== ':memory:') {
      await mkdir(dirname(filename), { recursive: true });
    }
    const sqlite = new SQLite(filename);
    if (wal) {
      sqlite.pragma('journal_mode = WAL');
    }
    return sqlite;
  });

  const db = run(() => {
    const dialect = new SqliteDialect({ database: sqlite });

    return new Kysely<D>({
      dialect,
      plugins: [new CamelCasePlugin(), new ParseJSONResultsPlugin()],
      log: (event) => {
        const prefix = '[sql]';
        const ms = `${round(event.queryDurationMillis)}ms`;
        const sql = event.query.sql;
        if (event.level === 'error') {
          console.error(prefix, ms, sql, event.error);
        } else {
          console.log(prefix, ms, sql);
        }
      },
    });
  });

  const schema = run(() => {
    const generate = async () => {
      // https://github.com/RobinBlomberg/kysely-codegen/blob/master/src/generator/generator/singularizer.ts#L20
      // `sharp` for some reason doesn't have path prop there
      Object.values(require.cache)
        .filter((mod) => mod && !mod.path)
        .forEach((mod) => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (mod as any).path = '';
        });

      const dialect = new CodegenSqliteDialect();
      return await generateSchema({
        db,
        dialect,
        runtimeEnums: false,
        singularize: true,
        camelCase: true,
        typeOnlyImports: true,
        skipAutogeneratedFileComment: true,
      });
    };

    return {
      generate,
    };
  });

  const migrate = run(() => {
    const getMigrator = () => {
      return new Migrator({
        db: db,
        provider: new FileMigrationProvider({
          fs,
          path,
          migrationFolder: migrations,
          import: (module) => import(/* @vite-ignore */ module),
        }),
      });
    };

    const toLatest = async () => {
      const { error, results } = await getMigrator().migrateToLatest();

      results?.forEach((it) => {
        if (it.status === 'Success') {
          console.log(`Migration ${it.migrationName} was executed successfully`);
        } else if (it.status === 'Error') {
          console.log(`Failed to execute migration ${it.migrationName}`);
        }
      });

      if (error) {
        console.log(`Failed to migrate to the latest revision: ${error}`);
        return false;
      } else {
        if (results?.length) {
          console.log('Migrated to latest revision');
        } else {
          console.log('No new migrations found');
        }
      }
      return true;
    };

    return {
      toLatest,
    };
  });

  return {
    filename,
    sqlite,
    db,
    schema,
    migrate,
  };
};

export type DatabaseServices<D = unknown> = Awaited<ReturnType<typeof createDatabaseServices<D>>>;
export type Database<D = unknown> = DatabaseServices<D>['db'];
