// @ts-expect-error Has no better-sqlite3 type
import SQLite from 'better-sqlite3';
import { mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { CamelCasePlugin, Kysely, ParseJSONResultsPlugin, SqliteDialect } from 'kysely';
import { generate as generateSchema, SqliteDialect as CodegenSqliteDialect } from 'kysely-codegen';
import fs from 'node:fs/promises';
import path from 'node:path';
import { FileMigrationProvider, Migrator } from 'kysely/migration';
import { round, run } from '../../utils/utils.ts';
import type { Logger } from '../utils.ts';

export type CreateDatabaseServicesOptions = {
  file: string;
  wal?: boolean;
  logger?: Logger;
};

export const createDatabaseServices = async <D = unknown>(opts: CreateDatabaseServicesOptions) => {
  const { file: filename, wal = true, logger } = opts;

  const sqlite = await run(async () => {
    if (filename !== ':memory:') {
      await mkdir(dirname(filename), { recursive: true });
    }
    const sqlite = new SQLite(filename);
    if (wal) {
      sqlite.pragma('journal_mode = WAL');
    }
    return sqlite;
  });

  const db = run(() => {
    const dialect = new SqliteDialect({ database: sqlite });

    return new Kysely<D>({
      dialect,
      plugins: [new CamelCasePlugin(), new ParseJSONResultsPlugin()],
      log: (event) => {
        const ms = `${round(event.queryDurationMillis)}ms`;
        const sql = event.query.sql;
        if (event.level === 'error') {
          logger?.error('sql', ms, sql, event.error);
        } else {
          logger?.info('sql', ms, sql);
        }
      },
    });
  });

  const schema = run(() => {
    const generate = async () => {
      // https://github.com/RobinBlomberg/kysely-codegen/blob/master/src/generator/generator/singularizer.ts#L20
      // `sharp` for some reason doesn't have path prop there
      Object.values(require.cache)
        .filter((mod) => mod && !mod.path)
        .forEach((mod) => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (mod as any).path = '';
        });

      const dialect = new CodegenSqliteDialect();
      return await generateSchema({
        db,
        dialect,
        runtimeEnums: false,
        singularize: true,
        camelCase: true,
        typeOnlyImports: true,
        skipAutogeneratedFileComment: true,
      });
    };

    return {
      generate,
    };
  });

  const migrate = ({ migrations }: { migrations: string }) => {
    const getMigrator = () => {
      return new Migrator({
        db: db,
        provider: new FileMigrationProvider({
          fs,
          path,
          migrationFolder: migrations,
          import: (module) => import(/* @vite-ignore */ module),
        }),
      });
    };

    const toLatest = async () => {
      const { error, results } = await getMigrator().migrateToLatest();
      results?.forEach((it) => {
        if (it.status === 'Success') {
          logger?.info('db', `Migration ${it.migrationName} was executed successfully`);
        } else if (it.status === 'Error') {
          logger?.info('db', `Failed to execute migration ${it.migrationName}`);
        }
      });
      if (error) {
        logger?.info('db', `Failed to migrate to the latest revision: ${error}`);
        return false;
      } else {
        if (results?.length) {
          logger?.info('db', 'Migrated to latest revision');
        } else {
          logger?.info('db', 'No new migrations found');
        }
      }
      return true;
    };

    return {
      toLatest,
    };
  };

  const as = <D>() => {
    return db as unknown as Kysely<D>;
  };

  return {
    filename,
    sqlite,
    db,
    as,
    schema,
    migrate,
  };
};

export type DatabaseServices<D = unknown> = Awaited<ReturnType<typeof createDatabaseServices<D>>>;
export type Database<D = unknown> = DatabaseServices<D>['db'];
