/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface File {
  contentType: string;
  id: string;
  name: string;
  size: number;
}

export interface Index {
  backgroundColor: string;
  backgroundId: string | null;
  description: string;
  id: string;
  indexBackgroundColor: string;
  indexTextColor: string;
  textColor: string;
  title: string;
}

export interface DB {
  files: File;
  index: Index;
}
