/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface File {
  contentType: string;
  id: string;
  name: string;
  size: number;
}

export interface Index {
  backgroundId: string | null;
  id: string;
  title: string;
}

export interface DB {
  files: File;
  index: Index;
}
