/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface File {
  id: string;
  name: string;
  variants: string;
}

export interface Gallery {
  id: string;
  name: Generated<string>;
  permalink: Generated<string>;
}

export interface Index {
  backgroundColor: string;
  backgroundId: string | null;
  backgroundOffset: number;
  description: string;
  id: string;
  indexBackgroundColor: string;
  indexTextColor: string;
  textColor: string;
  title: string;
}

export interface DB {
  files: File;
  galleries: Gallery;
  index: Index;
}
