import { generate as generateSchema, SqliteDialect as CodegenSqliteDialect } from 'kysely-codegen';
import fs from 'node:fs/promises';
import path from 'node:path';
import { FileMigrationProvider, Migrator } from 'kysely/migration';
import { run } from '../utils/utils.ts';
import { log, outro } from '@clack/prompts';
import type { Kysely } from 'kysely';

export type CreateDatabaseToolsOptions = {
  db: Kysely<unknown>;
};

export const createDatabaseTools = async (opts: CreateDatabaseToolsOptions) => {
  const { db } = opts;

  const schema = run(() => {
    const generate = async () => {
      // // https://github.com/RobinBlomberg/kysely-codegen/blob/master/src/generator/generator/singularizer.ts#L20
      // // `sharp` for some reason doesn't have path prop there
      // Object.values(require.cache)
      //   .filter((mod) => mod && !mod.path)
      //   .forEach((mod) => {
      //     // eslint-disable-next-line @typescript-eslint/no-explicit-any
      //     (mod as any).path = '';
      //   });

      const dialect = new CodegenSqliteDialect();
      return await generateSchema({
        db,
        dialect,
        runtimeEnums: false,
        singularize: true,
        camelCase: true,
        typeOnlyImports: true,
        skipAutogeneratedFileComment: true,
      });
      return '';
    };

    return {
      generate,
    };
  });

  const migrate = ({ migrations }: { migrations: string }) => {
    const getMigrator = () => {
      return new Migrator({
        db: db,
        provider: new FileMigrationProvider({
          fs,
          path,
          migrationFolder: migrations,
        }),
      });
    };

    const toLatest = async () => {
      const { error, results } = await getMigrator().migrateToLatest();
      results?.forEach((it) => {
        if (it.status === 'Success') {
          log.info(`Migration ${it.migrationName} was executed successfully`);
        } else if (it.status === 'Error') {
          log.info(`Failed to execute migration ${it.migrationName}`);
        }
      });
      if (error) {
        log.info(`Failed to migrate to the latest revision: ${error}`);
        return false;
      } else {
        if (results?.length) {
          outro('Migrated to latest revision');
        } else {
          outro('No new migrations found');
        }
      }
      return true;
    };

    return {
      toLatest,
    };
  };

  return {
    schema,
    migrate,
  };
};
