/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface File {
  contentType: string;
  id: string;
  name: string;
  size: number;
}

export interface DB {
  files: File;
}
